# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crawler.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CrawlerWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("*{  \n"
"    font-family:微软雅黑;\n"
"    font-size:20px;\n"
"    color: #1d649c;\n"
"}\n"
"QPushButton{\n"
"    border:1px solid #1d649c;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_weather = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_weather.setObjectName("pushButton_weather")
        self.verticalLayout.addWidget(self.pushButton_weather)
        self.pushButton_news = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_news.setObjectName("pushButton_news")
        self.verticalLayout.addWidget(self.pushButton_news)
        self.pushButton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.verticalLayout.addWidget(self.pushButton_Exit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_weather = QtWidgets.QWidget()
        self.page_weather.setObjectName("page_weather")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_weather)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_province = QtWidgets.QComboBox(self.page_weather)
        self.comboBox_province.setObjectName("comboBox_province")
        self.horizontalLayout.addWidget(self.comboBox_province)
        self.label_province = QtWidgets.QLabel(self.page_weather)
        self.label_province.setObjectName("label_province")
        self.horizontalLayout.addWidget(self.label_province)
        self.comboBox_city = QtWidgets.QComboBox(self.page_weather)
        self.comboBox_city.setObjectName("comboBox_city")
        self.horizontalLayout.addWidget(self.comboBox_city)
        self.label_city = QtWidgets.QLabel(self.page_weather)
        self.label_city.setObjectName("label_city")
        self.horizontalLayout.addWidget(self.label_city)
        self.comboBox_county = QtWidgets.QComboBox(self.page_weather)
        self.comboBox_county.setObjectName("comboBox_county")
        self.horizontalLayout.addWidget(self.comboBox_county)
        self.label_county = QtWidgets.QLabel(self.page_weather)
        self.label_county.setObjectName("label_county")
        self.horizontalLayout.addWidget(self.label_county)
        self.comboBox_figure = QtWidgets.QComboBox(self.page_weather)
        self.comboBox_figure.setObjectName("comboBox_figure")
        self.horizontalLayout.addWidget(self.comboBox_figure)
        self.label_figure = QtWidgets.QLabel(self.page_weather)
        self.label_figure.setObjectName("label_figure")
        self.horizontalLayout.addWidget(self.label_figure)
        self.pushButton_query = QtWidgets.QPushButton(self.page_weather)
        self.pushButton_query.setObjectName("pushButton_query")
        self.horizontalLayout.addWidget(self.pushButton_query)
        self.pushButton_update = QtWidgets.QPushButton(self.page_weather)
        self.pushButton_update.setObjectName("pushButton_update")
        self.horizontalLayout.addWidget(self.pushButton_update)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.page_weather)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_tu = QtWidgets.QLabel(self.page_weather)
        self.label_tu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tu.setObjectName("label_tu")
        self.verticalLayout_2.addWidget(self.label_tu)
        self.verticalLayout_2.setStretch(2, 1)
        self.stackedWidget.addWidget(self.page_weather)
        self.page_news = QtWidgets.QWidget()
        self.page_news.setObjectName("page_news")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_news)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_column = QtWidgets.QLabel(self.page_news)
        self.label_column.setObjectName("label_column")
        self.horizontalLayout_3.addWidget(self.label_column)
        self.comboBox_column = QtWidgets.QComboBox(self.page_news)
        self.comboBox_column.setObjectName("comboBox_column")
        self.horizontalLayout_3.addWidget(self.comboBox_column)
        self.label_title = QtWidgets.QLabel(self.page_news)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_3.addWidget(self.label_title)
        self.comboBox_title = QtWidgets.QComboBox(self.page_news)
        self.comboBox_title.setObjectName("comboBox_title")
        self.horizontalLayout_3.addWidget(self.comboBox_title)
        self.pushButton_query_2 = QtWidgets.QPushButton(self.page_news)
        self.pushButton_query_2.setObjectName("pushButton_query_2")
        self.horizontalLayout_3.addWidget(self.pushButton_query_2)
        self.pushButton_update_2 = QtWidgets.QPushButton(self.page_news)
        self.pushButton_update_2.setObjectName("pushButton_update_2")
        self.horizontalLayout_3.addWidget(self.pushButton_update_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.page_news)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser_title = QtWidgets.QTextBrowser(self.page_news)
        self.textBrowser_title.setObjectName("textBrowser_title")
        self.verticalLayout_3.addWidget(self.textBrowser_title)
        self.textBrowser_content = QtWidgets.QTextBrowser(self.page_news)
        self.textBrowser_content.setObjectName("textBrowser_content")
        self.verticalLayout_3.addWidget(self.textBrowser_content)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 9)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.stackedWidget.addWidget(self.page_news)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "每日资讯"))
        self.pushButton_weather.setText(_translate("MainWindow", "今日天气"))
        self.pushButton_news.setText(_translate("MainWindow", "今日新闻"))
        self.pushButton_Exit.setText(_translate("MainWindow", "返回菜单"))
        self.label_province.setText(_translate("MainWindow", "省"))
        self.label_city.setText(_translate("MainWindow", "市"))
        self.label_county.setText(_translate("MainWindow", "县"))
        self.label_figure.setText(_translate("MainWindow", "图"))
        self.pushButton_query.setText(_translate("MainWindow", "查询"))
        self.pushButton_update.setText(_translate("MainWindow", "更新"))
        self.label_tu.setText(_translate("MainWindow", "正在加载"))
        self.label_column.setText(_translate("MainWindow", "栏目："))
        self.label_title.setText(_translate("MainWindow", "标题："))
        self.pushButton_query_2.setText(_translate("MainWindow", "查询"))
        self.pushButton_update_2.setText(_translate("MainWindow", "更新"))
        self.textBrowser_title.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_content.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
