# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogInAndSignUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_LogInAndSignUp(object):
    def setupUi(self, Form_LogInAndSignUp):
        Form_LogInAndSignUp.setObjectName("Form_LogInAndSignUp")
        Form_LogInAndSignUp.resize(497, 355)
        Form_LogInAndSignUp.setStyleSheet("* { \n"
"    font-family:微软雅黑;\n"
"    font-size:30px;\n"
"    color: #1d649c ;\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form_LogInAndSignUp)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget_LogInAndSignUp = QtWidgets.QTabWidget(Form_LogInAndSignUp)
        self.tabWidget_LogInAndSignUp.setObjectName("tabWidget_LogInAndSignUp")
        self.tab_LogIn = QtWidgets.QWidget()
        self.tab_LogIn.setObjectName("tab_LogIn")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_LogIn)
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_LogIn = QtWidgets.QFormLayout()
        self.formLayout_LogIn.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_LogIn.setObjectName("formLayout_LogIn")
        self.label_LogInID = QtWidgets.QLabel(self.tab_LogIn)
        self.label_LogInID.setObjectName("label_LogInID")
        self.formLayout_LogIn.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_LogInID)
        self.lineEdit_LogInID = QtWidgets.QLineEdit(self.tab_LogIn)
        self.lineEdit_LogInID.setObjectName("lineEdit_LogInID")
        self.formLayout_LogIn.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_LogInID)
        self.label_LogInPW = QtWidgets.QLabel(self.tab_LogIn)
        self.label_LogInPW.setObjectName("label_LogInPW")
        self.formLayout_LogIn.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_LogInPW)
        self.lineEdit_LogInPW = QtWidgets.QLineEdit(self.tab_LogIn)
        self.lineEdit_LogInPW.setObjectName("lineEdit_LogInPW")
        self.formLayout_LogIn.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_LogInPW)
        self.verticalLayout.addLayout(self.formLayout_LogIn)
        self.pushButton_LogIn = QtWidgets.QPushButton(self.tab_LogIn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_LogIn.sizePolicy().hasHeightForWidth())
        self.pushButton_LogIn.setSizePolicy(sizePolicy)
        self.pushButton_LogIn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_LogIn.setObjectName("pushButton_LogIn")
        self.verticalLayout.addWidget(self.pushButton_LogIn)
        self.tabWidget_LogInAndSignUp.addTab(self.tab_LogIn, "")
        self.tab_SignUp = QtWidgets.QWidget()
        self.tab_SignUp.setObjectName("tab_SignUp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_SignUp)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_SignUp = QtWidgets.QFormLayout()
        self.formLayout_SignUp.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_SignUp.setObjectName("formLayout_SignUp")
        self.label_SignUpID = QtWidgets.QLabel(self.tab_SignUp)
        self.label_SignUpID.setObjectName("label_SignUpID")
        self.formLayout_SignUp.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_SignUpID)
        self.label_SignUpPW = QtWidgets.QLabel(self.tab_SignUp)
        self.label_SignUpPW.setObjectName("label_SignUpPW")
        self.formLayout_SignUp.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_SignUpPW)
        self.label_SignUpPW2 = QtWidgets.QLabel(self.tab_SignUp)
        self.label_SignUpPW2.setObjectName("label_SignUpPW2")
        self.formLayout_SignUp.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_SignUpPW2)
        self.label_SignUpUser = QtWidgets.QLabel(self.tab_SignUp)
        self.label_SignUpUser.setObjectName("label_SignUpUser")
        self.formLayout_SignUp.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_SignUpUser)
        self.lineEdit_SignUpID = QtWidgets.QLineEdit(self.tab_SignUp)
        self.lineEdit_SignUpID.setObjectName("lineEdit_SignUpID")
        self.formLayout_SignUp.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_SignUpID)
        self.lineEdit_SignUpUser = QtWidgets.QLineEdit(self.tab_SignUp)
        self.lineEdit_SignUpUser.setObjectName("lineEdit_SignUpUser")
        self.formLayout_SignUp.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_SignUpUser)
        self.lineEdit_SignUpPW = QtWidgets.QLineEdit(self.tab_SignUp)
        self.lineEdit_SignUpPW.setObjectName("lineEdit_SignUpPW")
        self.formLayout_SignUp.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_SignUpPW)
        self.lineEdit_SignUpPW2 = QtWidgets.QLineEdit(self.tab_SignUp)
        self.lineEdit_SignUpPW2.setObjectName("lineEdit_SignUpPW2")
        self.formLayout_SignUp.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_SignUpPW2)
        self.verticalLayout_2.addLayout(self.formLayout_SignUp)
        self.pushButton_SignUp = QtWidgets.QPushButton(self.tab_SignUp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SignUp.sizePolicy().hasHeightForWidth())
        self.pushButton_SignUp.setSizePolicy(sizePolicy)
        self.pushButton_SignUp.setObjectName("pushButton_SignUp")
        self.verticalLayout_2.addWidget(self.pushButton_SignUp)
        self.tabWidget_LogInAndSignUp.addTab(self.tab_SignUp, "")
        self.verticalLayout_3.addWidget(self.tabWidget_LogInAndSignUp)

        self.retranslateUi(Form_LogInAndSignUp)
        self.tabWidget_LogInAndSignUp.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form_LogInAndSignUp)

    def retranslateUi(self, Form_LogInAndSignUp):
        _translate = QtCore.QCoreApplication.translate
        Form_LogInAndSignUp.setWindowTitle(_translate("Form_LogInAndSignUp", "登录与注册"))
        self.label_LogInID.setText(_translate("Form_LogInAndSignUp", "账号"))
        self.label_LogInPW.setText(_translate("Form_LogInAndSignUp", "密码"))
        self.pushButton_LogIn.setText(_translate("Form_LogInAndSignUp", "登录"))
        self.tabWidget_LogInAndSignUp.setTabText(self.tabWidget_LogInAndSignUp.indexOf(self.tab_LogIn), _translate("Form_LogInAndSignUp", "登录"))
        self.label_SignUpID.setText(_translate("Form_LogInAndSignUp", "账号"))
        self.label_SignUpPW.setText(_translate("Form_LogInAndSignUp", "密码"))
        self.label_SignUpPW2.setText(_translate("Form_LogInAndSignUp", "确认密码"))
        self.label_SignUpUser.setText(_translate("Form_LogInAndSignUp", "用户名"))
        self.pushButton_SignUp.setText(_translate("Form_LogInAndSignUp", "注册"))
        self.tabWidget_LogInAndSignUp.setTabText(self.tabWidget_LogInAndSignUp.indexOf(self.tab_SignUp), _translate("Form_LogInAndSignUp", "注册"))
