# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, Ui_MenuWindow):
        Ui_MenuWindow.setObjectName("Ui_MenuWindow")
        Ui_MenuWindow.resize(611, 432)
        Ui_MenuWindow.setStyleSheet("*{  \n"
"    font-family:微软雅黑;\n"
"    font-size:30px;\n"
"    color: #1d649c;\n"
"}\n"
"QPushButton{\n"
"    border:1px solid #1d649c;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Ui_MenuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.verticalLayout.addWidget(self.label_welcome)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ChatNetwork = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ChatNetwork.setObjectName("pushButton_ChatNetwork")
        self.horizontalLayout.addWidget(self.pushButton_ChatNetwork)
        self.pushButton_Settings = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Settings.setObjectName("pushButton_Settings")
        self.horizontalLayout.addWidget(self.pushButton_Settings)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Query = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Query.setObjectName("pushButton_Query")
        self.horizontalLayout_2.addWidget(self.pushButton_Query)
        self.pushButton_AiFriends = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AiFriends.setObjectName("pushButton_AiFriends")
        self.horizontalLayout_2.addWidget(self.pushButton_AiFriends)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_author = QtWidgets.QLabel(self.centralwidget)
        self.label_author.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_author.setObjectName("label_author")
        self.verticalLayout.addWidget(self.label_author)
        Ui_MenuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_MenuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 46))
        self.menubar.setObjectName("menubar")
        Ui_MenuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_MenuWindow)
        self.statusbar.setObjectName("statusbar")
        Ui_MenuWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_MenuWindow)
        QtCore.QMetaObject.connectSlotsByName(Ui_MenuWindow)

    def retranslateUi(self, Ui_MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        Ui_MenuWindow.setWindowTitle(_translate("Ui_MenuWindow", "菜单"))
        self.label_welcome.setText(_translate("Ui_MenuWindow", "欢迎使用多功能聊天系统"))
        self.pushButton_ChatNetwork.setText(_translate("Ui_MenuWindow", "网络聊天"))
        self.pushButton_Settings.setText(_translate("Ui_MenuWindow", "设置参数"))
        self.pushButton_Query.setText(_translate("Ui_MenuWindow", "每日资讯"))
        self.pushButton_AiFriends.setText(_translate("Ui_MenuWindow", "虚拟伙伴"))
        self.label_author.setText(_translate("Ui_MenuWindow", "作者--刘培富"))
# import img_rc
